### PR TITLE
Please review my assignment

### PR DESCRIPTION
**Pull request by denstadnyk**

### CODE REVIEW

**Comment by jb2849** [comment]
good

**Comment by yingchen95** [comment]
good

**Comment by danielfrangel** [comment]
nice job

**Comment by ANILREDDY36** [comment]
well done

**Comment by avulashukla** [comment]
good work

**Comment by bibhuti1234** [comment]
good work

**Comment by jiahongdu** [comment]
good!

**Comment by klmnavneet** [comment]
good

**Comment by renuka1611** [comment]
good

**Comment by Buzz-afk** [comment]
good

**Comment by sagarika12123** [comment]
good

**Comment by swirlsupriya** [comment]
well done!!

**Comment by alicetinna311** [comment]
good job

**Comment by Sixu922** [comment]
great

**Comment by varsha-max** [comment]
coursera assignment 3. review it.

**Comment by Ludmila1965** [comment]
coursera assignment 3. review it.

**Comment by IrinaVeretelnik** [comment]
makeCacheMatrix <- function(x = matrix()) {
inv<-NULL
set<-fucntion(y){
        x<<-y
        inv<<-NULL
}
get<-fucntion()x
setInverse<-function(solveMatrix) inv<<-solveMatrix
getInverse<-function() inv
list(set=set, get=get, setInverse=setInverse, getInverse=getInverse)
}

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
}inv<-x$getInverse()
if(!is.null(inv)){
        message("getting cached data")
        return(inv)
}
data<-x$get()
inv<-solve(data)
x$setInverse(inv)
inv
}

**Comment by weiyizz** [comment]
good

**Comment by priyankathumma2** [comment]
Coursera assignment 3 review it

**Comment by StefaniaBran** [comment]
Please review my 3rd assignment.

**Comment by Lakshay2308** [comment]
hey

**Comment by Amanfly** [comment]
Good

**Comment by Nagaraj-gcet** [comment]
good.

**Comment by marufa18** [comment]
First commit

**Comment by kspavithra1982** [comment]
Good

**Comment by subhashini2409** [comment]
good work

**Comment by subhashini2409** [comment]
good

**Comment by minimanimoh** [comment]
goood

**Comment by Aishwarya-1-4** [comment]
##the below function is used to explain the formation of cache matrix that includes inverse function with 
## j being NULL vector.it also includes a list containing clear data for the function being run.

makeCacheMatrix <- function(x = matrix()) {
  j <- NULL
  set <- function(y){
    x <<- y
    j <<- NULL
  }
  get <- function()x
  setInverse <- function(inverse) j <<- inverse
  getInverse <- function() j 
  list(set = set, get = get, 
       setInverse = setInverse, 
       getInverse = getInverse)
}

##the below code is generated to form a cachesolve with filter function including a character vector to 
##form the not logical function,if function and return function.

cacheSolve <- function(x, ...) {
  y<<- x
  j <- x$getInverse()
  if(!is.null(j)){
    message("getting cached data")
    return(j)
  }
  mat <- x$get()
  j <- solve(mat,...)
  x$setInverse(j)
  j
}

**Comment by Aishwarya-1-4** [comment]
images.githubusercontent.com/65302332/82121944-42db6680-97ae-11ea-8d20-95ce47cd4680.png)

**Comment by wang-yunzhi** [comment]
good

**Comment by Aishwarya-1-4** [comment]
(https://user-images.githubusercontent.com/65302332/82126964-dff9c780-97cd-11ea-9c0d-0487360f0f3e.png)

**Comment by mayank284** [comment]
good

**Comment by satyam-shandilya** [comment]
good

**Comment by RAQIB-1** [comment]
good

**Comment by genesis-san** [comment]
funciones.R

**Comment by rb715** [comment]
please review my assignment
[makeCacheMatrix.docx](https://github.com/rdpeng/ProgrammingAssignment2/files/4878945/makeCacheMatrix.docx)

**Comment by jcdvz** [comment]
good

**Comment by raghush86** [comment]
good

**Comment by Bipanchi-crypto** [comment]
please review my assignment 
[MakeCacheMatrix.docx](https://github.com/rdpeng/ProgrammingAssignment2/files/5029203/MakeCacheMatrix.docx)

**Comment by Julianbarba** [comment]
Well done!

**Comment by tanishq-ctrl** [comment]
good job

**Comment by tripti-hub20** [comment]
good

**Comment by Nidhisv21** [comment]
nice work

**Comment by pranithacse** [comment]
good

**Comment by pranithacse** [comment]
good

**Comment by praghyatrivedi** [comment]
Good work!!

**Comment by Bablukumar7351** [comment]
Week 3 programming assignment_b.r
setwd('C:/Users/rubind1/Documents/Coursera-R')
##
## I simply set the input x as a matrix
## and then set the solved value "s" as a null
## then I changed every reference to "mean" to "solve"
makeCacheMatrix <- function(x = matrix(sample(1:100,9),3,3)) {
  s <- NULL
  set <- function(y) {
    x <<- y
    s <<- NULL
  }
  get <- function() x
  setsolve <- function(solve) s <<- solve
  getsolve <- function() s
  list(set = set, get = get,
       setsolve = setsolve,
       getsolve = getsolve)
}
##
## Same here, changed "mean" to "solve" and "m" to "s"
cacheSolve <- function(x, ...) {
  s <- x$getsolve()
  if(!is.null(s)) {
    message("getting inversed matrix")
    return(s)
  }
  data <- x$get()
  s <- solve(data, ...)
  x$setsolve(s)
  s
}

**Comment by touffor** [comment]
Good

**Comment by touffor** [comment]
Good

**Comment by sl9512** [comment]
Good Job!

**Comment by AriaXwG** [comment]
nice

**Comment by Sonya0122** [comment]
good

**Pull request closed without merging**
