### PR TITLE
Work done!

### PR DESCRIPTION
**Pull request by denstadnyk**

### CODE REVIEW

**Comment by suvo240** [comment]
## Caching the Inverse of a Matrix:
## Matrix inversion is usually a costly computation and there may be some 
## benefit to caching the inverse of a matrix rather than compute it repeatedly.
## Below are a pair of functions that are used to create a special object that 
## stores a matrix and caches its inverse.

## This function creates a special "matrix" object that can cache its inverse.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setInverse <- function(inverse) inv <<- inverse
  getInverse <- function() inv
  list(set = set,
       get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


## This function computes the inverse of the special "matrix" created by 
## makeCacheMatrix above. If the inverse has already been calculated (and the 
## matrix has not changed), then it should retrieve the inverse from the cache.

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  inv <- x$getInverse()
  if (!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  mat <- x$get()
  inv <- solve(mat, ...)
  x$setInverse(inv)
  inv
}

**Comment by danielfrangel** [comment]
nice

**Comment by ANILREDDY36** [comment]
good job!

**Comment by avulashukla** [comment]
good job

**Comment by jiahongdu** [comment]
good

**Comment by ShalluArora** [comment]
nice

**Comment by YogeshPatodia** [comment]
nicw

**Comment by YogeshPatodia** [comment]
nice

**Comment by klmnavneet** [comment]
nice

**Comment by renuka1611** [comment]
good

**Comment by Buzz-afk** [comment]
good

**Comment by yamroh** [comment]
Good work

**Comment by sagarika12123** [comment]
good

**Comment by rubygrover** [comment]
Good work

**Comment by Sixu922** [comment]
well donw

**Comment by weiyizz** [comment]
good work

**Comment by Nagaraj-gcet** [comment]
good

**Comment by kspavithra1982** [comment]
Good

**Comment by minimanimoh** [comment]
good

**Comment by huishin2020** [comment]
Good.

**Comment by RAQIB-1** [comment]
good

**Comment by manojmanu297** [comment]
Caching the Inverse of a Matrix:
Matrix inversion is usually a time taking activity and there may be some
the benefit to caching the inverse of a matrix rather than compute it repeatedly. pair of functions that are used to create a special object that stores a matrix and caches its inverse.
This function creates a special "matrix" object.

makeCacheMatrix <- function(x = matrix()){
               inv <- NULL
               set <- function(y){
                 x <<- y
                 inv <<- NULL
               }
               get <- function() {x}
               SetInverse <- function(inverse) {inv <<- inverse}
               getInverse <- function() {inv}
               list(set = set, get = get, setInverse = setInverse, getInverse = getInverse)
}

The following function returns the inverse of cache matrix. And evaluates the inverse of a matrix

cacheSolve <- function(x, ...){
  inv <- x$getInverse()
  if(!is.null(inv)){
    message("getting cached data")
    return(inv)
  }
  mat <- x$get()
  inv <- solve(mat, ...)
  x$setInverse(inv)
  inv
}

**Comment by manojmanu297** [comment]
please review the assignment

**Comment by RAQIB-1** [comment]
I have completed the code but couldn't submit the assignment via GitHub . I
have installed GitHub desktop 64 bit but there is a kernel 32dll file
missing shows. I checked Google but couldn't find the solution. I don't
know what Wii I do now.

**Comment by shrashtip** [comment]
## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

makeCacheMatrix <- function(x = matrix()) {

}


## Write a short comment describing this function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
}

**Comment by maryamosama217** [comment]
good job

**Comment by kushwantkaur** [comment]
excellent

**Comment by tanishq-ctrl** [comment]
good job

**Comment by omoaletsane** [comment]
### Programming Assignment II
		### Creat Special Matrix
makeCacheMatrix <- function(x = matrix()) {
  j <- NULL
  set <- function(y){
  x <<- y	### Assignment Operator in the Parent Environment 
  j <<- NULL
  }
  get <- function()x
  setInverse <- function(inverse) j <<- inverse
  getInverse <- function() j 
  list(set = set, get = get, 
  setInverse = setInverse, 
  getInverse = getInverse)
}
		### Cache the Matrix
cacheSolve <- function(x, ...) {
		### Return a matrix that is the inverse of 'x'
  j <- x$getInverse()
  if(!is.null(j)){
  message("getting cached data")
  return(j)
  }
  mat <- x$get()
  j <- solve(mat,...)
  x$setInverse(j)
  j
}

**Comment by wangbup34** [comment]
good

**Comment by tiffanywsx** [comment]
nice

**Pull request closed without merging**
